### ISSUE TITLE
Question: vs2022 samples already updated to hip 6.1 sdk but rocm win sdk still at 5.7.. correct?

### ISSUE THREAD

**Issue by oscarbg** [amd/rocm-examples#104]
Latest commit implies or rocm sdk 6.1 for windows is coming soon or must use vs2019 projects? Correct..

**Comment by The-Lord-of-Owls** [comment]
might be a good idea to revert [this](https://github.com/ROCm/rocm-examples/commit/9c978e05d05270b95c2a5b6700b82ccc4f90960e) commit until 6.1 SDK is actually available to be used. Otherwise issues start showing up. For example changing the build toolset inside VS breaks the solution, and the only option that doesn't break the solution is manually going into solution files and changing 6.1 to 5.7

**Comment by Naraenda** [comment]
CC @emankov Can we revert that commit?

**Comment by emankov** [comment]
Hello @Naraenda,

Nope, The `develop` branch is the default branch for the latest changes. The `release/rocm-rel-5.7`  needs to be created instead.
