### ISSUE TITLE
GPU Isolation Configs such as ROCR_VISIBLE_DEVICES are not working

### ISSUE THREAD

**Issue by PPPW** [amd/rocm-examples#86]
Is there a way to run `hip_bandwidth` with a particular GPU? ROCm has [GPU isolation settings](https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html), however none of the configs (ROCR_VISIBLE_DEVICES, GPU_DEVICE_ORDINAL, HIP_VISIBLE_DEVICES, etc.) seem to work. For example, I expect GPU 3 to run the bandwidth test with the following command:

```
HIP_VISIBLE_DEVICES=3 ~/rocm-examples/HIP-Basic/bandwidth/hip_bandwidth -memcpy htod dtoh
```

From this command: `watch -n 1 rocm-smi --showpidgpus --showpids`, I saw `hip_bandwidth` is always using GPU 0, so the GPU isolation configs are not taken.

I just followed the README to install "rocm-examples": git clone, make. Could you let me know what is the correct way to run the ROCm examples with a selected set of GPUs? Thank you!

**Comment by Snektron** [comment]
This is strange, because all of those seem correct. I can't reproduce the issue with either `HIP_VISIBLE_DEVICES` or `ROCR_VISIBLE_DEVICES`, it seems to pick the right device.

Regardless, the example also offers a `--device` option which you can use to pass the device(s) that should be used with the example: `hip_bandwidth -memcpy htod dtoh -device 3`.

**Comment by PPPW** [comment]
Thank you @Snektron, the device option worked for me, and sounds like the `HIP_VISIBLE_DEVICES` is not related to code in this repo, I'll resolve this issue and look into that later
